TEST_VALUE:
  name: "dev_cookie"
FEISHU_CONFIG:
  FEISHU_URL: https://open.feishu.cn/open-apis
  FEISHU_API_HOST: https://open.feishu.cn
  FEISHU_APP_ID: cli_a3f0a3f03e38d00d
  FEISHU_APP_SECRET: ev21McwcQ1iUxrc5vu9P5brPrFsi8U2K
APP_TOKEN_CACHE_KEY: APP_TOKEN_CACHE_KEY
USER_REFRESH_TOKEN_CACHE_KEY: USER_REFRESH_TOKEN_CACHE_KEY
USER_TOKEN_CACHE_KEY: USER_TOKEN_CACHE_KEY
MONGODB_CONFIG:
  name: "nest_gateway"          # 自定义次数据库链接名称
  type: mongodb                      # 数据库链接类型
  url: "mongodb://localhost:27017"   # 数据库链接地址
  username: "root"             # 数据库链接用户名
  password: "Smartzheng1993"                 # 数据库链接密码
  database: "nest_gateway"           # 数据库名
  entities: "mongo"                  # 自定义加载类型
  useUnifiedTopology: true
  logging: false                     # 数据库打印日志
  synchronize: true                  # 是否开启同步数据表功能
MYSQL_CONFIG:
  name: "nest_gateway"
  type: "mysql"
  host: "localhost"
  port: 3306
  username: "root"
  password: "Smartzheng1993"
  database: "nest_gateway"
  entities: "mysql" # 这里的命名一定要跟 MongoDB 里面的配置命名区分开
  synchronize: true
REDIS_CONFIG:
  host: "localhost"  # redis 链接
  port: 6379         # redis 端口
#  auth: "Smartzheng1993"       # redis 连接密码
  db: 1              # redis 数据库
