TEST_VALUE:
  name: "test_cookie"
FEISHU_CONFIG:
  FEISHU_URL: https://open.feishu.cn/open-apis
  FEISHU_API_HOST: https://open.feishu.cn
  FEISHU_APP_ID: cli_xxx
  FEISHU_APP_SECRET: xxx
APP_TOKEN_CACHE_KEY: xxx
